=== Dimitrysaf/LEOS-Greek/modules/domain/src/main/resources/schema/structure/structure_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://eu.europa.ec.digit.leos.pilot/schema/"
           xmlns="http://eu.europa.ec.digit.leos.pilot/schema/">

    <xs:element name="structure">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="version" type="xs:string"/>
                <xs:element name="tocItems" type="tocItems"/>
                <xs:element name="numberingConfigs" type="numberingConfigs"/>
                <xs:element name="alternateConfigs" type="alternateConfigs"/>
                <xs:element name="tocRules" type="tocRules" minOccurs="0"/>
                <xs:element name="documentRules" type="documentRules" minOccurs="0"/>
                <xs:element name="referenceConfig" type="referenceConfig" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tocItems">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="tocItem" type="tocItem"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tocItem">
        <xs:sequence>
            <xs:element name="aknTag" type="aknTag"/>
            <xs:element name="root" type="xs:boolean" default="false"/>
            <xs:element name="higherElement" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="draggable" type="xs:boolean" default="false"/>
            <xs:element name="childrenAllowed" type="xs:boolean" default="false"/>
            <xs:element name="display" type="xs:boolean" default="false"/>
            <xs:element name="itemNumber" type="optionsType" default="none"/>
            <xs:element name="autoNumbering" type="autoNumbering" minOccurs="0"/>
            <xs:element name="soleNumbering" type="autoNumbering" minOccurs="0"/>
            <xs:element name="itemHeading" type="optionsType" default="none"/>
            <xs:element name="itemDescription" type="xs:boolean" default="false"/>
            <xs:element name="numberEditable" type="xs:boolean" default="false"/>
            <xs:element name="contentDisplayed" type="xs:boolean" default="false"/>
            <xs:element name="deletable" type="xs:boolean" default="false"/>
            <xs:element name="rootItemDeletable" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="notAddable" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="numWithType" type="xs:boolean" default="false"/>
            <xs:element name="expandedByDefault" type="xs:boolean" default="false"/>
            <xs:element name="sameParentAsChild" type="xs:boolean" default="false"/>
            <xs:element name="onlySameParentAsChild" type="xs:boolean" default="false" minOccurs="0"/>
            <xs:element name="tocItemTypes" type="tocItemTypes" minOccurs="0"/>
            <xs:element name="parentNameNumberingTypeDependency" type="aknTag" minOccurs="0"/>
            <xs:element name="profiles" type="profiles" minOccurs="0"/>
            <xs:element name="editable" type="xs:boolean" default="false"/>
            <xs:element name="addSoftAttr" type="xs:boolean" default="true" minOccurs="0"/>
            <xs:element name="template" type="xs:string" minOccurs="0"/>
            <xs:element name="maxDepth" type="xs:string" minOccurs="0"/>
            <xs:element name="actionsPosition" type="actionPositions" default="RIGHT" minOccurs="0"/>
            <xs:element name="dapInfos" type="dapInfos" minOccurs="0"/>
            <xs:element name="depthEnabled" type="xs:boolean" minOccurs="0" default="false"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dapInfos">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="dapInfo" type="dapInfo"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dapInfo">
        <xs:sequence>
            <xs:element name="dapInfoLabel" type="xs:string" default=""/>
            <xs:element name="dapInfoURL" type="xs:string" default=""/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="autoNumbering">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="langNumConfig" type="langNumConfig"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="soleNumbering">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="langNumConfig" type="langNumConfig"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="langNumConfig">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="numberingType" type="numberingType"/>
        </xs:sequence>
        <xs:attribute name="langGroup" type="xs:string" use="required"/>
        <xs:attribute name="auto" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:simpleType name="optionsType" final="restriction">
        <xs:annotation>
            <xs:documentation>Option values used to configure an element like itemNumber and itemHeading
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="none"/>
            <xs:enumeration value="mandatory"/>
            <xs:enumeration value="optional"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="numberingConfigs">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="numberingConfig" type="numberingConfig"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="numberingConfig">
        <xs:annotation>
            <xs:documentation>Number configuration. Example: 1), 1., (a), etc</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="type" type="numberingType" default="NONE"  minOccurs="0"/>
            <xs:element name="label" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="numbered" type="xs:boolean" default="false"/>
            <xs:element name="prefix" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="suffix" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="suffixInEnd" type="xs:boolean" default="true" minOccurs="0"/>
            <xs:element name="sequence" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="description" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="regex" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="regexJS" type="xs:string" default="" minOccurs="0"/>
            <xs:element name="msgValidationError" type="xs:string" default="" minOccurs="0"/>
            <!-- ATTENTION: Make sure that all configNumbers indicated in the list levels are present in the plugin listItemNumberModule.js -->
            <xs:element name="levels" type="levels" minOccurs="0"/>
            <xs:element name="level" type="xs:string" default="" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tocItemType">
        <xs:sequence>
            <xs:element name="name" type="tocItemTypeName"/>
            <xs:element name="attribute" type="attribute" minOccurs="0"/>
            <xs:element name="subElementNumberingConfigs" type="subElementNumberingConfigs"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="attribute">
        <xs:sequence>
            <xs:element name="attributeName" type="xs:string"/>
            <xs:element name="attributeValue" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tocItemTypeName" final="restriction">
        <xs:annotation>
            <xs:documentation>Names of tocItems' types. For instance: definition articles or regular articles
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGULAR"/>
            <xs:enumeration value="DEFINITION"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="subElementNumberingConfigs">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="subElementNumberingConfig" type="subElementNumberingConfig"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="subElementNumberingConfig">
        <xs:sequence>
            <xs:element name="subElement" type="aknTag"/>
            <xs:element name="langNumConfig" type="langNumConfig" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="alternateConfigs">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="alternateConfig" type="alternateConfig"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="alternateConfig">
        <xs:sequence>
            <xs:element name="type" type="aknTag"/>
            <xs:element name="profile" type="xs:string" default=""/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="profiles">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="profile" type="profile"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="profile">
        <xs:sequence>
            <xs:element name="elementSelector" minOccurs="0" type="xs:string"/>
            <xs:element name="profileName" type="xs:string" default=""/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="levels">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="level" type="level"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="level">
        <xs:sequence>
            <xs:element name="depth" type="xs:int"/>
            <xs:element name="numberingType" type="numberingType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="numberingType" final="restriction">
        <xs:annotation>
            <xs:documentation>All types of numbering. Add here the new type</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="SOLE_ARTICLE"/>
            <xs:enumeration value="SOLE_ARTICLE_CYRILLIC"/>
            <xs:enumeration value="SOLE_ARTICLE_GREEK"/>
            <xs:enumeration value="SOLE_RECITAL"/>
            <xs:enumeration value="SOLE_RECITAL_CYRILLIC"/>
            <xs:enumeration value="SOLE_RECITAL_GREEK"/>
            <xs:enumeration value="ARABIC"/>
            <xs:enumeration value="ARABIC_POSTFIXDOT"/>
            <xs:enumeration value="ARABIC_POSTFIXDOT_NODOT_END"/>
            <xs:enumeration value="ARABIC_PARENTHESIS"/>
            <xs:enumeration value="GREEK"/>
            <xs:enumeration value="GREEK_POSTFIXDOT"/>
            <xs:enumeration value="GREEK_PARENTHESIS"/>
            <xs:enumeration value="ALPHA_LOWER_PARENTHESIS"/>
            <xs:enumeration value="GREEK_ALPHA_LOWER_PARENTHESIS"/>
            <xs:enumeration value="CYRILLIC_ALPHA_LOWER_PARENTHESIS"/>
            <xs:enumeration value="ROMAN_LOWER_PARENTHESIS"/>
            <xs:enumeration value="ROMAN_UPPER"/>
            <xs:enumeration value="BULLET_BLACK_CIRCLE"/>
            <xs:enumeration value="BULLET_WHITE_CIRCLE"/>
            <xs:enumeration value="BULLET_BLACK_SQUARE"/>
            <xs:enumeration value="BULLET_WHITE_SQUARE"/>
            <xs:enumeration value="BULLET_NUM"/>
            <xs:enumeration value="INDENT"/>
            <xs:enumeration value="HIGHER_ELEMENT_NUM"/>
            <xs:enumeration value="POINT_NUM"/>
            <xs:enumeration value="POINT_NUM_DEF"/>
            <xs:enumeration value="POINT_NUM_CYRILLIC"/>
            <xs:enumeration value="POINT_NUM_DEF_CYRILLIC"/>
            <xs:enumeration value="POINT_NUM_GREEK"/>
            <xs:enumeration value="POINT_NUM_DEF_GREEK"/>
            <xs:enumeration value="LEVEL_NUM"/>
            <xs:enumeration value="DIVISION_NUM"/>
            <xs:enumeration value="ROMAN_UPPER_POSTFIXDOT"/>
            <xs:enumeration value="ROMAN_UPPER_POSTFIXPARENTHESIS"/>
            <xs:enumeration value="ALPHA_UPPER_POSTFIXDOT"/>
            <xs:enumeration value="ALPHA_UPPER_POSTFIXPARENTHESIS"/>
            <xs:enumeration value="TEXTUAL"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="higherDivisions">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="type" type="higherDivisionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="higherDivisionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="part"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="chapter"/>
            <xs:enumeration value="section"/>
            <xs:enumeration value="recitals"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lowerElementType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="recital"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="lowerDivisions">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="type" type="lowerDivisionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="lowerDivisionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="division"/>
            <xs:enumeration value="article"/>
            <xs:enumeration value="paragraph"/>
            <xs:enumeration value="subparagraph"/>
            <xs:enumeration value="list"/>
            <xs:enumeration value="point"/>
            <xs:enumeration value="indent"/>
            <xs:enumeration value="subpoint"/>
            <xs:enumeration value="alinea"/>
            <xs:enumeration value="recital"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="aknTag" final="restriction">
        <xs:annotation>
            <xs:documentation>All toc tags</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="doc"/>
            <xs:enumeration value="preface"/>
            <xs:enumeration value="docstage"/>
            <xs:enumeration value="doctype"/>
            <xs:enumeration value="docpurpose"/>
            <xs:enumeration value="preamble"/>
            <xs:enumeration value="citations"/>
            <xs:enumeration value="citation"/>
            <xs:enumeration value="recitals"/>
            <xs:enumeration value="recital"/>
            <xs:enumeration value="body"/>
            <xs:enumeration value="part"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="chapter"/>
            <xs:enumeration value="section"/>
            <xs:enumeration value="division"/>
            <xs:enumeration value="article"/>
            <xs:enumeration value="paragraph"/>
            <xs:enumeration value="subparagraph"/>
            <xs:enumeration value="list"/>
            <xs:enumeration value="point"/>
            <xs:enumeration value="indent"/>
            <xs:enumeration value="subpoint"/>
            <xs:enumeration value="alinea"/>
            <xs:enumeration value="clause"/>
            <xs:enumeration value="conclusions"/>

            <xs:enumeration value="mainBody"/>
            <xs:enumeration value="tblock"/>
            <xs:enumeration value="blockContainer"/>
            <xs:enumeration value="num"/>
            <xs:enumeration value="heading"/>
            <xs:enumeration value="crossHeading"/>
            <xs:enumeration value="block"/>
            <xs:enumeration value="level"/>
            <xs:enumeration value="content"/>
            <xs:enumeration value="aknp"/>
            <xs:enumeration value="table"/>
            <xs:enumeration value="division"/>

            <xs:enumeration value="formula"/>

            <xs:enumeration value="coverPage"/>
            <xs:enumeration value="longTitle"/>
            <xs:enumeration value="docPurpose"/>
            <xs:enumeration value="inline"/>

            <xs:enumeration value="signature"/>
            <xs:enumeration value="block"/>
            <xs:enumeration value="organization"/>
            <xs:enumeration value="role"/>
            <xs:enumeration value="person"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tocRules">
        <xs:sequence>
            <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="tocItem" minOccurs="0" type="aknTag"/>
                        <xs:element name="list" minOccurs="0" type="tocIdList"/>
                        <xs:element name="order" minOccurs="0" type="siblingsOrder"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="documentRules">
        <xs:sequence>
            <xs:element name="rule" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="description" type="xs:string"/>
                        <xs:element name="type" type="xs:string"/>
                        <xs:element name="tocItem" type="aknTag" minOccurs="0"/>
                        <xs:element name="higherDivisions" type="higherDivisions" minOccurs="0"/>
                        <xs:element name="lowerDivisions" type="lowerDivisions" minOccurs="0"/>
                        <xs:element name="scope" type="xs:string"/>
                        <xs:element name="exception" minOccurs="0" type="tocIdList"/>
                        <xs:element name="errorMessage" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="referenceConfig">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="refConfig" type="refConfig"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="refConfig">
        <xs:sequence>
            <xs:element name="internalRef" type="xs:boolean"/>
            <xs:element name="authorialNote" type="xs:boolean"/>
        </xs:sequence>
        <xs:attribute name="language" type="xs:string" default="default"/>
    </xs:complexType>

    <xs:complexType name="tocItemTypes">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="tocItemType" type="tocItemType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tocIdList">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="tocItem" type="aknTag"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="siblingsOrder">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="list" type="tocIdList"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="actionPositions" final="restriction">
        <xs:annotation>
            <xs:documentation>Action positions is used to configure action button position for any element profile
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="LEFT"/>
            <xs:enumeration value="RIGHT"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Dimitrysaf/LEOS-Greek/tools/cmis/chemistry-opencmis-server-inmemory/src/main/resources/leos/templates/os/structure_04.xml
<?xml version="1.0" encoding="UTF-8"?>
<structure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://eu.europa.ec.digit.leos.pilot/schema/"
           xsi:schemaLocation="http://eu.europa.ec.digit.leos.pilot/schema/ structure_1.xsd">

    <name>structure_04.xml</name>
    <description>Structure used for Annex with article</description>
    <version>1</version>

    <tocItems>
        <tocItem>
            <aknTag>preface</aknTag>
            <root>true</root>
            <draggable>false</draggable>
            <childrenAllowed>false</childrenAllowed>
            <display>true</display>
            <itemNumber>none</itemNumber>
            <itemHeading>none</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>false</numberEditable>
            <contentDisplayed>false</contentDisplayed>
            <deletable>false</deletable>
            <numWithType>false</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>NONE</numberingType>
            <editable>false</editable>
        </tocItem>

        <tocItem>
            <aknTag>mainBody</aknTag>
            <root>true</root>
            <draggable>false</draggable>
            <childrenAllowed>true</childrenAllowed>
            <display>true</display>
            <itemNumber>none</itemNumber>
            <itemHeading>none</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>false</numberEditable>
            <contentDisplayed>false</contentDisplayed>
            <deletable>false</deletable>
            <numWithType>false</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>NONE</numberingType>
            <editable>false</editable>
        </tocItem>

        <tocItem>
            <aknTag>part</aknTag>
            <root>false</root>
            <draggable>true</draggable>
            <childrenAllowed>true</childrenAllowed>
            <display>true</display>
            <itemNumber>mandatory</itemNumber>
            <autoNumbering>false</autoNumbering>
            <itemHeading>mandatory</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>true</numberEditable>
            <contentDisplayed>false</contentDisplayed>
            <deletable>true</deletable>
            <numWithType>true</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>ROMAN_UPPER</numberingType>
            <editable>false</editable>
            <template><![CDATA[<part xml:id="_${id}"><num>${num}</num><heading>${heading}</heading></part>]]></template>
        </tocItem>

        <tocItem>
            <aknTag>title</aknTag>
            <root>false</root>
            <draggable>true</draggable>
            <childrenAllowed>true</childrenAllowed>
            <display>true</display>
            <itemNumber>mandatory</itemNumber>
            <autoNumbering>false</autoNumbering>
            <itemHeading>mandatory</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>true</numberEditable>
            <contentDisplayed>false</contentDisplayed>
            <deletable>true</deletable>
            <numWithType>true</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>ROMAN_UPPER</numberingType>
            <editable>false</editable>
            <template><![CDATA[<title xml:id="_${id}"><num>${num}</num><heading>${heading}</heading></title>]]></template>
        </tocItem>

        <tocItem>
            <aknTag>chapter</aknTag>
            <root>false</root>
            <draggable>true</draggable>
            <childrenAllowed>true</childrenAllowed>
            <display>true</display>
            <itemNumber>mandatory</itemNumber>
            <autoNumbering>false</autoNumbering>
            <itemHeading>mandatory</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>true</numberEditable>
            <contentDisplayed>false</contentDisplayed>
            <deletable>true</deletable>
            <numWithType>true</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>HIGHER_ELEMENT_NUM</numberingType>
            <editable>false</editable>
            <template><![CDATA[<chapter xml:id="_${id}"><num>${num}</num><heading>${heading}</heading></chapter>]]></template>
        </tocItem>

        <tocItem>
            <aknTag>section</aknTag>
            <root>false</root>
            <draggable>true</draggable>
            <childrenAllowed>true</childrenAllowed>
            <display>true</display>
            <itemNumber>mandatory</itemNumber>
            <autoNumbering>false</autoNumbering>
            <itemHeading>mandatory</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>true</numberEditable>
            <contentDisplayed>false</contentDisplayed>
            <deletable>true</deletable>
            <numWithType>true</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>ARABIC_PARENTHESIS</numberingType>
            <editable>false</editable>
            <template><![CDATA[<section xml:id="_${id}"><num>${num}</num><heading>${heading}</heading></section>]]></template>
        </tocItem>

        <tocItem>
            <aknTag>heading</aknTag>
            <root>false</root>
            <draggable>false</draggable>
            <childrenAllowed>false</childrenAllowed>
            <display>false</display>
            <itemNumber>none</itemNumber>
            <autoNumbering>false</autoNumbering>
            <itemHeading>none</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>false</numberEditable>
            <contentDisplayed>false</contentDisplayed>
            <deletable>false</deletable>
            <numWithType>false</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>NONE</numberingType>
            <profiles>
                <profile>
                    <elementSelector>heading:not(article heading)</elementSelector>
                    <profileName>inlineAknHeading</profileName>
                </profile>
            </profiles>
            <editable>true</editable>
        </tocItem>

        <tocItem>
            <aknTag>article</aknTag>
            <root>false</root>
            <draggable>true</draggable>
            <childrenAllowed>false</childrenAllowed>
            <display>true</display>
            <itemNumber>mandatory</itemNumber>
            <autoNumbering>true</autoNumbering>
            <itemHeading>optional</itemHeading>
            <itemDescription>true</itemDescription>
            <numberEditable>false</numberEditable>
            <contentDisplayed>true</contentDisplayed>
            <deletable>true</deletable>
            <numWithType>true</numWithType>
            <expandedByDefault>true</expandedByDefault>
            <sameParentAsChild>false</sameParentAsChild>
            <numberingType>ARABIC</numberingType>
            <tocItemTypes>
                <tocItemType>
                    <name>REGULAR</name>
                    <subElementNumberingConfigs>
                        <subElementNumberingConfig>
                            <subElement>point</subElement>
                            <numberingType>POINT_NUM</numberingType>
                        </subElementNumberingConfig>
                        <subElementNumberingConfig>
                            <subElement>indent</subElement>
                            <numberingType>POINT_NUM</numberingType>
                        </subElementNumberingConfig>
                    </subElementNumberingConfigs>
                </tocItemType>
                <tocItemType>
                    <name>DEFINITION</name>
                    <attribute>
                        <attributeName>refersTo</attributeName>
                        <attributeValue>~_ART_DEF</attributeValue>
                    </attribute>
                    <subElementNumberingConfigs>
                        <subElementNumberingConfig>
                            <subElement>point</subElement>
                            <numberingType>POINT_NUM_DEF</numberingType>
                        </subElementNumberingConfig>
                        <subElementNumberingConfig>
                            <subElement>indent</subElement>
                            <numberingType>POINT_NUM_DEF</numberingType>
                        </subElementNumberingConfig>
                    </subElementNumberingConfigs>
                </tocItemType>
            </tocItemTypes>
            <profiles>
                <profile>
                    <profileName>inlineAknArticle</profileName>
                </profile>
            </profiles>
            <editable>true</editable>
            <template><![CDATA[<article xml:id="_${id}"><num leos:editable="false">${num}</num><heading>${heading}</heading><paragraph xml:id="_${id}-par1"><num>1.</num><content><p>${default.content.text}</p></content></paragraph></article>]]></template>
        </tocItem>

        <tocItem>
            <aknTag>paragraph</aknTag>
            <root>false</root>
            <draggable>false</draggable>
            <childrenAllowed>true</childrenAllowed>
            <display>false</display>
            <itemNumber>optional</itemNumber>
            <autoNumbering>true</autoNumbering>
